#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinApp.Android.Resource", IsApplication=true)]

namespace XamarinApp.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int accent = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int gray = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int light_gray = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int primary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int primaryDark = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int window_background = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int buyButton = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int descriptionTextView = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int imageView = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int listView1 = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int nameTextView = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int price = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int priceTextView = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int specificatonListView = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int title = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int valueTextView = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int eBayListRow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ItemDetail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SpecificationListRow = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int description = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int endtime = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int price = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int quantity = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int specifications = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int text = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int title = 2131034118;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int heading_text = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
